### ISSUE TITLE
why data class is hidden?

### ISSUE THREAD

**Issue by HiroyukiTamura** [renggli/dart-more#1]
for example, class `Indexed` in `package:more/src/iterable/indexed.dart` can't be accessed from other package.
but I want to use class for generics just like `indexed<E>(list).map((Indexed<E> item) {}`
any solution?
thanks in advance.

**Comment by renggli** [comment]
This is an oversight, fixed in cec2e6a8f69a9104aff0bbfdc9e35a6e776ae1a8 and 1.18.1.
