### ISSUE TITLE
IntegerRange(500).contains(1000) is true

### ISSUE THREAD

**Issue by Keithcat1** [renggli/dart-more#12]
## configuration
Dart: 1.18
OS: Windows 10 (64-bit)
More version: 3.8.2
## example code
```dart
import "package:more/collection.dart";

void main() {
	final range = IntegerRange(500);
	print(range.contains(1000)); // true
}
```

**Comment by renggli** [comment]
Thank you for reporting, this is a serious oversight caused by incomplete tests (fixed that as well).
