### ISSUE TITLE
IntegerRange(10, 35, 10) isn't returning [10, 20, 30]

### ISSUE THREAD

**Issue by mykdavies** [renggli/dart-more#13]
Hi Lukas, Long time no speak, hope you're doing well!

I love this library, but there seems to be an issue in the logic in IntegerRange for non-default step sizes. Sorry to be reporting this just after 3.9.0 got released 😄 

Cheers, Michael

**Comment by renggli** [comment]
Hi Michael, 

Nice to hear from you again! Thanks for the bug report, very strange, looking into it.

Cheers,
Lukas

**Comment by renggli** [comment]
Created a new release: `more 3.9.1`.

**Comment by mykdavies** [comment]
Great service for a Saturday! 😉
