### ISSUE TITLE
`printer/null.dart` breaks DDC builds

### ISSUE THREAD

**Issue by BrokenR3C0RD** [renggli/dart-more#14]
I'm using this package for the iterable extensions, but ran into an issue when trying to use it on web using `webdev serve`.

When running with development settings, I get the following error: `Uncaught SyntaxError: Unexpected token 'null' (at bimap.sound.ddc.js:108:7)`. This is caused by https://github.com/dart-lang/sdk/issues/39595, which apparently never caught the eyes of the Dart team enough to fix. The package works properly in webdev release builds.

When I cloned locally, renamed `null.dart` to `null_printer.dart` and made the other necessary changes, the package worked as intended.

**Comment by renggli** [comment]
Ahh interesting, thanks for reporting ... I observed that problem too, but wasn't eager enough to investigate the true problem. I'll rename the file as you suggest.
