### ISSUE TITLE
[BitList] Consider making use of efficient implementations of popcount, ctz and clz if they become available.

### ISSUE THREAD

**Issue by modulovalue** [renggli/dart-more#15]
For reference: https://github.com/dart-lang/sdk/issues/52673

**Comment by renggli** [comment]
Nothing this package can do as long as these operations are not available. In the meantime I suggest to use the implementations provided in [lib/src/math/bit.dart](https://github.com/renggli/dart-more/blob/main/lib/src/math/bit.dart) or create a pull request if some functionality is missing.
