### ISSUE TITLE
 meta ^1.11.0 and every version of flutter from sdk depends on meta 1.10.0 

### ISSUE THREAD

**Issue by sgehrman** [renggli/dart-more#16]
Because more >=4.1.0 depends on meta ^1.11.0 and every version of flutter from sdk depends on meta 1.10.0, more >=4.1.0 is incompatible with flutter from sdk.
So, because shared_package depends on both flutter from sdk and more ^4.2.0, version solving failed.

I'm on the latest stable branch

**Comment by renggli** [comment]
From a practical standpoint I am unable to test with older package versions. New releases are always published with the latest stable dependencies. Consider sticking with an older version of this package until your dependencies have caught up; or using [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
