### ISSUE TITLE
Unicode Bidi Category matchers

### ISSUE THREAD

**Issue by amake** [renggli/dart-more#17]
I have a need to match characters with a particular Bidi Category: https://www.unicode.org/reports/tr9/#Table_Bidirectional_Character_Types

The data file appears to have the same format as DerivedGeneralCategory:
https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedBidiClass.txt

Would you accept a PR to add this to the existing collection of UnicodeCharMatchers?

**Comment by renggli** [comment]
Certainly, that sounds good.
