### ISSUE TITLE
Some dependencies incompatible with current Flutter stable (3.24.3)

### ISSUE THREAD

**Issue by amake** [renggli/dart-more#19]
When trying to consume the `more` package in a Flutter project using the current stable release (3.24.3), there are conflicts involving the `meta` and `collections` packages:

```
% flutter pub get
Resolving dependencies... 
Note: meta is pinned to version 1.15.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of more from path depends on meta ^1.16.0 and every version of flutter_test from sdk depends on meta
  1.15.0, more from path is incompatible with flutter_test from sdk.
So, because org_flutter depends on both flutter_test from sdk and more from path, version solving failed.
```

I tried downgrading to meta 1.15.0 and collection 1.18.0 locally, and both `dart analyze` and `dart test` succeeded. Would you be willing to downgrade these deps for the time being?

**Comment by renggli** [comment]
Sure, send a pull request.

The problem I encounter repeatedly with this (and my other packages) is that I am using stable Dart, `dart pub outdated` is suggesting to upgrade dependencies, and that I have no easy way (?) to test older dependencies :-(

**Comment by amake** [comment]
Yeah I don't see a good way to keep Flutter compatibility if you aren't using Flutter :(

**Comment by amake** [comment]
Thanks for merging!

Would you consider cutting a release sometime soon? I am consuming `more` in a published library, which can't depend on an unpublished dependency.

**Comment by renggli** [comment]
I published https://pub.dev/packages/more/versions/4.4.0.

**Comment by amake** [comment]
Thank you!
