### ISSUE TITLE
Always Nulls Last for Ascending or Descending sort

### ISSUE THREAD

**Issue by awhitford** [renggli/dart-more#4]
I am having trouble getting Ascending vs Descending sort working, always with _nulls last_.  Imagine code like this:
```dart
    final orderingAsc = Ordering.natural<String>().nullsLast;
    final orderingDesc = Ordering.natural<String>().reversed.nullsLast;
...
              final sorter = sortAscending ? orderingAsc : orderingDesc;
              return sorter.compare(s1, s2);
```

I would expect null values ALWAYS to be at the BOTTOM -- then the non-null values will be sorted in Ascending or Descending order, depending on the `sortAscending` flag.

_What am I doing wrong?_

**Comment by renggli** [comment]
I've added a test trying to reproduce your example: https://github.com/renggli/dart-more/commit/c58c8b5b291ef6b21b7b0907059e02a1b83c0c69. Both orderings work for me as expected.

**Comment by awhitford** [comment]
@renggli Apologies, but I figured out what my issue was:  I had _Empty Strings_, not _Null_ values.  I knew I was doing something wrong, but sometimes you don't see it right away.

Adding tests is always wise, and a good reference.  I appreciate your quick attention.
