### ISSUE TITLE
Ordering example incorrect [documentation]

### ISSUE THREAD

**Issue by awhitford** [renggli/dart-more#5]
Minor documentation bug for [Ordering class](https://pub.dev/documentation/more/latest/more.ordering/Ordering-class.html).  The example:

```dart
var natural = new Ordering.natural();
natural.compare(1, 2);  // 1
```

Wouldn't the compare result be `-1` signifying that 1 is less than 2?

**Comment by renggli** [comment]
Thank you for reporting. The example was not only buggy, but it also was no longer working with Dart 2.0+.
