### ISSUE TITLE
Multiset difference method should take Iterable<Object?> as argument

### ISSUE THREAD

**Issue by Wikiwix** [renggli/dart-more#8]
`Multiset`'s `difference function takes  `Iterable<Object>` which was fine before null safety. But with null safety this unnecessarily limits the uses.
For example 

```dart
Multiset<E> diffSample<E>(Multiset<E> multiset, Iterable<E> iterable) =>  multiset.difference(iterable);
```
will fail unless you force `E` to extend from `Object`.

I guess this logic will apply to other collection related code, but did not search for them.

**Comment by renggli** [comment]
Thank you for reporting, let me know if you spot other cases.
