### ISSUE TITLE
Q: Stream utilities PR

### ISSUE THREAD

**Issue by pihentagy** [renggli/dart-more#9]
Hi!

Are you interested in a PR, which provides sliding window, but for streams, similar to https://github.com/renggli/dart-more/blob/main/lib/src/iterable/window.dart?

thanks

**Comment by renggli** [comment]
Sure, that sounds great!

**Comment by pihentagy** [comment]
Nice. Where should it be in the more lib?

**Comment by renggli** [comment]
Answered in https://github.com/renggli/dart-more/pull/10#issuecomment-1000284778.
